name: auxo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_heatmap_calendar: ^1.0.5
  flutter_slidable: ^4.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.10
  hive_generator: ^2.0.1
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # Add assets
  assets:
    - assets/
    - assets/logo.png

# Splash screen configuration
flutter_native_splash:
  color: "#f5f5f5"  
  image: assets/logo.png
  android_12:
    image: assets/logo.png
    color: "#f5f5f5"
  android_gravity: center
  ios_content_mode: center

# App icon configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
